packages:
  - !include common/wifi.yaml
  - !include waveshare/waveshare-esp32-s3-touch-lcd-7-bl.yaml
  

esphome:
  name: "waveshare-test"
  friendly_name: "Display_1"  
 

time:
  - platform: homeassistant
    id: homeassistant_time

image:
  - file: images/main_bg.png
    id: main_background
    type: RGB565
    resize: 800x480

lvgl:
  pages:
    # ========== MAIN PAGE - Thermostat & Szenen ==========
    - id: main_page
      widgets:
        # Hintergrundbild (wenn definiert)
        - image:
            align: CENTER
            src: main_background
            width: 800
            height: 480
    
    # ========== LICHT PAGE ==========
    - id: light_page
      widgets:
        # Hintergrundbild
        - image:
            align: CENTER
            src: main_background
            width: 800
            height: 480
    
    # ========== ROLLADEN PAGE ==========
    - id: cover_page
      widgets:
        # Hintergrundbild
        - image:
            align: CENTER
            src: main_background
            width: 800
            height: 480

